package com.example.guardianangel;

import android.content.Context;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.RatingBar;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvException;

import java.io.FileReader;
import java.util.*;
import java.util.stream.Collectors;

public class SymptomsActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener {

    private float value;
    //private DatabaseWorking db_handler;
    private String text;
    private String te;
    private String [] symptomsList = {
            "ADHD",
            "AIDS Related Wasting",
            "AV Heart Block",
            "Abdominal Distension",
            "Abnormal Uterine Bleeding",
            "Abortion",
            "Acne",
            "Actinic Keratosis",
            "Acute Coronary Syndrome",
            "Acute Lymphoblastic Leukemia",
            "Acute Nonlymphocytic Leukemia",
            "Acute Otitis Externa",
            "Acute Promyelocytic Leukemia",
            "Addison's Disease",
            "Adrenocortical Insufficiency",
            "Adult Human Growth Hormone Deficiency",
            "Aggressive Behavi",
            "Agitated State",
            "Agitation",
            "Alcohol Dependence",
            "Alcohol Withdrawal",
            "Allergic Reactions",
            "Allergic Rhinitis",
            "Allergic Urticaria",
            "Allergies",
            "Alopecia",
            "Alpha-1 Proteinase Inhibitor Deficiency",
            "Alzheimer's Disease",
            "Amebiasis",
            "Amenorrhea",
            "Anal Fissure and Fistula",
            "Anal Itching",
            "Anaphylaxis",
            "Anaplastic Astrocytoma",
            "Anaplastic Oligodendroglioma",
            "Androgenetic Alopecia",
            "Anemia",
            "Anemia Associated with Chronic Renal Failure",
            "Anemia, Chemotherapy Induced",
            "Anemia, Sickle Cell",
            "Anesthesia",
            "Angina",
            "Angina Pectoris Prophylaxis",
            "Ankylosing Spondylitis",
            "Anorexia",
            "Antiphospholipid Syndrome",
            "Anxiety",
            "Anxiety and Stress",
            "Aphthous Ulce",
            "Arrhythmia",
            "Ascariasis",
            "Asperger Syndrome",
            "Aspergillosis, Aspergilloma",
            "Aspiration Pneumonia",
            "Asthma",
            "Asthma, Maintenance",
            "Asthma, acute",
            "Asystole",
            "Atherosclerosis",
            "Atopic Dermatitis",
            "Atrial Fibrillation",
            "Atrial Flutte",
            "Atrophic Urethritis",
            "Atrophic Vaginitis",
            "Auditory Processing Disorde",
            "Autism",
            "Autoimmune Hemolytic Anemia",
            "Autoimmune Hepatitis",
            "Avian Influenza",
            "B12 Nutritional Deficiency",
            "Back Pain",
            "Bacteremia",
            "Bacterial Endocarditis Prevention",
            "Bacterial Infection",
            "Bacterial Skin Infection",
            "Bacterial Vaginitis",
            "Barrett's Esophagus",
            "Basal Cell Carcinoma",
            "Behcet's Disease",
            "Benign Essential Trem",
            "Benign Prostatic Hyperplasia",
            "Benzodiazepine Withdrawal",
            "Biliary Cirrhosis",
            "Binge Eating Disorde",
            "Bipolar Disorde",
            "Birth Control",
            "Bladder Infection",
            "Bleeding Disorde",
            "Blepharitis",
            "Body Dysmorphic Disorde",
            "Bone infection",
            "Borderline Personality Disorde",
            "Bowel Preparation",
            "Brain Tum",
            "Breakthrough Pain",
            "Breast Cance",
            "Breast Cancer, Adjuvant",
            "Breast Cancer, Metastatic",
            "Breast Cancer, Palliative",
            "Breast Cancer, Prevention",
            "Bronchiectasis",
            "Bronchitis",
            "Bronchospasm Prophylaxis",
            "Bulimia",
            "Bullous Pemphigoid",
            "Burning Mouth Syndrome",
            "Burns, External",
            "Bursitis",
            "CMV Prophylaxis",
            "CNS Magnetic Resonance Imaging",
            "COPD",
            "COPD, Acute",
            "COPD, Maintenance",
            "Cachexia",
            "Campylobacter Gastroenteritis",
            "Cance",
            "Candida Urinary Tract Infection",
            "Candidemia",
            "Carcinoid Tum",
            "Cardiovascular Risk Reduction",
            "Cataplexy",
            "Cerebral Edema",
            "Cervical Dystonia",
            "Chlamydia Infection",
            "Chronic Eosinophilic Leukemia",
            "Chronic Fatigue Syndrome",
            "Chronic Idiopathic Constipation",
            "Chronic Inflammatory Demyelinating Polyradiculoneuropathy",
            "Chronic Lymphocytic Leukemia",
            "Chronic Myelogenous Leukemia",
            "Chronic Myofascial Pain",
            "Chronic Pain",
            "Chronic Pancreatitis",
            "Chronic Spasticity",
            "Clostridial Infection",
            "Cluster Headaches",
            "Coccidioidomycosis",
            "Cogan's Syndrome",
            "Cold Sores",
            "Cold Symptoms",
            "Colorectal Cance",
            "Computed Tomography",
            "Condylomata Acuminata",
            "Conjunctivitis",
            "Conjunctivitis, Allergic",
            "Conjunctivitis, Bacterial",
            "Constipation",
            "Constipation, Acute",
            "Constipation, Chronic",
            "Constipation, Drug Induced",
            "Corneal Refractive Surgery",
            "Coronary Artery Disease",
            "Costochondritis",
            "Cough",
            "Cough and Nasal Congestion",
            "Crohn's Disease",
            "Crohn's Disease, Acute",
            "Crohn's Disease, Maintenance",
            "Croup",
            "Cutaneous Candidiasis",
            "Cutaneous T-cell Lymphoma",
            "Cyclic Vomiting Syndrome",
            "Cyclothymic Disorde",
            "Cystic Fibrosis",
            "Dandruff",
            "Deep Neck Infection",
            "Deep Vein Thrombosis",
            "Deep Vein Thrombosis Prophylaxis after Hip Replacement Surgery",
            "Deep Vein Thrombosis Prophylaxis after Knee Replacement Surgery",
            "Deep Vein Thrombosis, First Event",
            "Deep Vein Thrombosis, Prophylaxis",
            "Deep Vein Thrombosis, Recurrent Event",
            "Delayed Puberty, Male",
            "Dementia",
            "Dental Abscess",
            "Depression",
            "Dercum's Disease",
            "Dermatitis",
            "Dermatitis Herpeti",
            "Dermatologic Lesion",
            "Dermatological Disorders",
            "Dermatomyositis",
            "Dermatophytosis",
            "Diabetes Insipidus",
            "Diabetes, Type 1",
            "Diabetes, Type 2",
            "Diabetic Kidney Disease",
            "Diabetic Macular Edema",
            "Diabetic Peripheral Neuropathy",
            "Diagnosis and Investigation",
            "Diaper Rash",
            "Diarrhea",
            "Diarrhea, Acute",
            "Diarrhea, Chronic",
            "Dientamoeba fragilis",
            "Dietary Fiber Supplementation",
            "Dietary Supplementation",
            "Dissociative Identity Disorde",
            "Diverticulitis",
            "Dry Eye Disease",
            "Dry Skin",
            "Dumping Syndrome",
            "Duodenal Ulce",
            "Dupuytren's contracture",
            "Dysautonomia",
            "Dyspareunia",
            "Dystonia",
            "Dysuria",
            "Ear Wax Impaction",
            "Ectopic Pregnancy",
            "Eczema",
            "Edema",
            "Ehrlichiosis",
            "Emergency Contraception",
            "Endometrial Cance",
            "Endometrial Hyperplasia",
            "Endometrial Hyperplasia, Prophylaxis",
            "Endometriosis",
            "Endoscopy or Radiology Premedication",
            "Enterocolitis",
            "Eosinophilic Esophagitis",
            "Epicondylitis, Tennis Elbow",
            "Epilepsy",
            "Erectile Dysfunction",
            "Erosive Esophagitis",
            "Euvolemic Hyponatremia",
            "Expectoration",
            "Extrapyramidal Reaction",
            "Eye Redness",
            "Eye Redness/Itching",
            "Eyelash Hypotrichosis",
            "GERD",
            "Gallbladder Disease",
            "Gas",
            "Gastric Ulcer Maintenance Treatment",
            "Gastritis/Duodenitis",
            "Gastroenteritis",
            "Gastrointestinal Decontamination",
            "Gastrointestinal Hemorrhage",
            "Gastrointestinal Stromal Tum",
            "Gastroparesis",
            "Gaucher Disease",
            "Gender Dysphoria",
            "Generalized Anxiety Disorde",
            "Giardiasis",
            "Gingivitis",
            "Glaucoma",
            "Glaucoma, Open Angle",
            "Glaucoma/Intraocular Hypertension",
            "Glioblastoma Multi",
            "Glioblastoma Multiforme",
            "Gonadotropin Inhibition",
            "Gonococcal Infection, Disseminated",
            "Gonococcal Infection, Uncomplicated",
            "Gout",
            "Gout, Acute",
            "Gouty Arthritis",
            "Granuloma Annulare",
            "HIV Infection",
            "Hairy Cell Leukemia",
            "Hashimoto's disease",
            "Head Injury",
            "Head Lice",
            "Head and Neck Cance",
            "Headache",
            "Heart Attack",
            "Heart Failure",
            "Helicobacter Pylori Infection",
            "Hemophilia B",
            "Hemorrhoids",
            "Hemorrhoids (pramoxine / zinc oxide)",
            "Hepatic Encephalopathy",
            "Hepatitis B",
            "Hepatitis C",
            "Hepatocellular Carcinoma",
            "Herbal Supplementation",
            "Hereditary Angioedema",
            "Herpes Simplex",
            "Herpes Simplex Dendritic Keratitis",
            "Herpes Simplex, Mucocutaneous/Immunocompetent Host",
            "Herpes Simplex, Mucocutaneous/Immunocompromised Host",
            "Herpes Simplex, Suppression",
            "Herpes Zoste",
            "Herpes Zoster, Prophylaxis",
            "Hiccups",
            "Hidradenitis Suppurativa",
            "High Blood Pressure",
            "High Cholesterol",
            "High Cholesterol, Familial Heterozygous",
            "High Cholesterol, Familial Homozygous",
            "Hirsutism",
            "Hot Flashes",
            "Human Papilloma Virus",
            "Human Papillomavirus Prophylaxis",
            "Hypercalcemia",
            "Hyperekplexia",
            "Hyperhidrosis",
            "Hyperkalemia",
            "Hyperlipoproteinemia",
            "Hyperlipoproteinemia Type III, Elevated beta-VLDL   IDL",
            "Hyperlipoproteinemia Type IIa, Elevated LDL",
            "Hyperlipoproteinemia Type IV, Elevated VLDL",
            "Hyperparathyroidism Secondary to Renal Impairment",
            "Hyperphosphatemia of Renal Failure",
            "Hyperprolactinemia",
            "Hypersomnia",
            "Hypertensive Emergency",
            "Hyperthyroidism",
            "Hypertriglyceridemia",
            "Hyperuricemia Secondary to Chemotherapy",
            "Hypoactive Sexual Desire Disorde",
            "Hypocalcemia",
            "Hypodermoclysis",
            "Hypoestrogenism",
            "Hypoglycemia",
            "Hypogonadism, Male",
            "Hypokalemic Periodic Paralysis",
            "Hypoparathyroidism",
            "Hypotension",
            "Hypothyroidism, After Thyroid Removal",
            "ICU Agitation",
            "Ichthyosis",
            "Idiopathic Thrombocytopenic Purpura",
            "Immunosuppression",
            "Impetig",
            "Indigestion",
            "Infection Prophylaxis",
            "Infectious Diarrhea",
            "Inflammatory Bowel Disease",
            "Inflammatory Conditions",
            "Influenza",
            "Influenza Prophylaxis",
            "Insomnia",
            "Insomnia, Stimulant-Associated",
            "Insulin Resistance Syndrome",
            "Intermittent Claudication",
            "Intermittent Explosive Disorde",
            "Interstitial Cystitis",
            "Intraabdominal Infection",
            "Intraocular Hypertension",
            "Iritis",
            "Iron Deficiency Anemia",
            "Irritable Bowel Syndrome",
            "Ischemic Stroke",
            "Ischemic Stroke, Prophylaxis",
            "Juvenile Idiopathic Arthritis",
            "Juvenile Rheumatoid Arthritis",
            "Keratitis",
            "Keratoconjunctivitis Sicca",
            "Keratosis",
            "Kidney Infections",
            "Labor Induction",
            "Labor Pain",
            "Lactation Augmentation",
            "Lactose Intolerance",
            "Left Ventricular Dysfunction",
            "Legionella Pneumonia",
            "Lennox-Gastaut Syndrome",
            "Leukemia",
            "Lewy Body Dementia",
            "Lichen Planus",
            "Lichen Sclerosus",
            "Light Anesthesia",
            "Light Sedation",
            "Linear IgA Disease",
            "Lipodystrophy",
            "Liver Magnetic Resonance Imaging",
            "Local Anesthesia",
            "Lyme Disease",
            "Lyme Disease, Arthritis",
            "Lyme Disease, Erythema Chronicum Migrans",
            "Lyme Disease, Neurologic",
            "Lymphocytic Colitis",
            "Lymphoma",
            "Macular Degeneration",
            "Macular Edema",
            "Major Depressive Disorde",
            "Malaria",
            "Malaria Prevention",
            "Malignant Glioma",
            "Mania",
            "Melanoma",
            "Melanoma, Metastatic",
            "Melasma",
            "Meniere's Disease",
            "Meningococcal Meningitis Prophylaxis",
            "Menopausal Disorders",
            "Menorrhagia",
            "Menstrual Disorders",
            "Methicillin-Resistant Staphylococcus Aureus Infection",
            "Microscopic polyangiitis",
            "Migraine",
            "Migraine Prevention",
            "Mild Cognitive Impairment",
            "Mitral Valve Prolapse",
            "Mononucleosis",
            "Motion Sickness",
            "Mountain Sickness / Altitude Sickness",
            "Mucositis",
            "Multiple Endocrine Adenomas",
            "Multiple Myeloma",
            "Multiple Sclerosis",
            "Mumps Prophylaxis",
            "Muscle Pain",
            "Muscle Spasm",
            "Muscle Twitching",
            "Myasthenia Gravis",
            "Mycobacterium avium-intracellulare, Treatment",
            "Mycoplasma Pneumonia",
            "Myelodysplastic Syndrome",
            "Myeloproliferative Disorders",
            "Myxedema Coma",
            "NSAID-Induced Gastric Ulce",
            "NSAID-Induced Ulcer Prophylaxis",
            "Narcolepsy",
            "Nasal Carriage of Staphylococcus aureus",
            "Nasal Congestion",
            "Nasal Polyps",
            "Nausea/Vomiting",
            "Nausea/Vomiting of Pregnancy",
            "Nausea/Vomiting, Chemotherapy Induced",
            "Nausea/Vomiting, Postoperative",
            "Nausea/Vomiting, Radiation Induced",
            "Neck Pain",
            "Nephrocalcinosis",
            "Nephrotic Syndrome",
            "Neuralgia",
            "Neuropathic Pain",
            "Neurosurgery",
            "Neutropenia",
            "Neutropenia Associated with Chemotherapy",
            "New Daily Persistent Headache",
            "Night Terrors",
            "Nightmares",
            "Nocturnal Leg Cramps",
            "Non-Hodgkin's Lymphoma",
            "Non-Small Cell Lung Cance",
            "Nonalcoholic Fatty Liver Disease",
            "Noninfectious Colitis",
            "Obesity",
            "Obsessive Compulsive Disorde",
            "Obstructive Sleep Apnea/Hypopnea Syndrome",
            "Occipital Neuralgia",
            "Onychomycosis, Fingernail",
            "Onychomycosis, Toenail",
            "Oophorectomy",
            "Ophthalmic Surgery",
            "Opiate Adjunct",
            "Opiate Dependence",
            "Opiate Withdrawal",
            "Opioid Overdose",
            "Opioid-Induced Constipation",
            "Oppositional Defiant Disorde",
            "Oral Thrush",
            "Oral and Dental Conditions",
            "Organ Transplant, Rejection Prophylaxis",
            "Osteoarthritis",
            "Osteolytic Bone Lesions of Multiple Myeloma",
            "Osteolytic Bone Metastases of Solid Tumors",
            "Osteoporosis",
            "Otitis Externa",
            "Otitis Media",
            "Ovarian Cance",
            "Ovarian Cysts",
            "Overactive Bladde",
            "Ovulation Induction",
            "Pain",
            "Pain/Feve",
            "Pancreatic Cance",
            "Pancreatic Exocrine Dysfunction",
            "Panic Disorde",
            "Paragonimus westermani, Lung Fluke",
            "Paranoid Disorde",
            "Parkinson's Disease",
            "Parkinsonian Trem",
            "Paroxysmal Supraventricular Tachycardia",
            "Patent Ductus Arteriosus",
            "Pathological Hypersecretory Conditions",
            "Pe",
            "Pediatric Growth Hormone Deficiency",
            "Pelvic Inflammatory Disease",
            "Pemphigus",
            "Peptic Ulce",
            "Percutaneous Coronary Intervention",
            "Performance Anxiety",
            "Perimenopausal Symptoms",
            "Period Pain",
            "Periodic Limb Movement Disorde",
            "Periodontitis",
            "Perioral Dermatitis",
            "Peripheral Arterial Disease",
            "Peripheral Neuropathy",
            "Persistent Depressive Disorde",
            "Pertussis",
            "Peyronie's Disease",
            "Pharyngitis",
            "Photoaging of the Skin",
            "Pinworm Infection (Enterobius vermicularis)",
            "Pityriasis rubra pilaris",
            "Plaque Psoriasis",
            "Pneumococcal Disease Prophylaxis",
            "Pneumonia",
            "Polycystic Ovary Syndrome",
            "Polycythemia Vera",
            "Porphyria",
            "Portal Hypertension",
            "Post Traumatic Stress Disorde",
            "Post-Cholecystectomy Diarrhea",
            "Postherpetic Neuralgia",
            "Postmenopausal Symptoms",
            "Postoperative Increased Intraocular Pressure",
            "Postoperative Ocular Inflammation",
            "Postoperative Pain",
            "Postpartum Breast Pain",
            "Postpartum Depression",
            "Postural Orthostatic Tachycardia Syndrome",
            "Pre-Exposure Prophylaxis",
            "Precocious Puberty",
            "Premature Lab",
            "Premature Ventricular Depolarizations",
            "Premenstrual Dysphoric Disorde",
            "Premenstrual Syndrome",
            "Prevention of Atherothrombotic Events",
            "Prevention of Bladder infection",
            "Prevention of Cardiovascular Disease",
            "Prevention of Dental Caries",
            "Prevention of Hypokalemia",
            "Prevention of Osteoporosis",
            "Prevention of Thromboembolism in Atrial Fibrillation",
            "Primary Immunodeficiency Syndrome",
            "Primary Nocturnal Enuresis",
            "Primary Ovarian Failure",
            "Progesterone Insufficiency",
            "Prostate Cance",
            "Prostatitis",
            "Prosthetic Heart Valves, Mechanical Valves - Thrombosis Prophylaxis",
            "Prosthetic Heart Valves, Tissue Valves - Thrombosis Prophylaxis",
            "Pruritus",
            "Pruritus of Partial Biliary Obstruction",
            "Pseudobulbar Affect",
            "Pseudogout, Prophylaxis",
            "Pseudotumor Cerebri",
            "Psoriasis",
            "Psoriatic Arthritis",
            "Psychosis",
            "Pulmonary Embolism",
            "Pulmonary Embolism, First Event",
            "Pulmonary Embolism, Recurrent Event",
            "Pulmonary Hypertension",
            "Pupillary Dilation",
            "Radionuclide Myocardial Perfusion Study",
            "Ramsay Hunt Syndrome",
            "Raynaud's Syndrome",
            "Reflex Sympathetic Dystrophy Syndrome",
            "Renal Cell Carcinoma",
            "Renal Transplant",
            "Restless Legs Syndrome",
            "Reversal of Nondepolarizing Muscle Relaxants",
            "Reversal of Opioid Sedation",
            "Rheumatoid Arthritis",
            "Rhinitis",
            "Rhinorrhea",
            "Rosacea",
            "SIADH",
            "Salivary Gland Cance",
            "Sarcoidosis",
            "Scabies",
            "Schilling Test",
            "Schistosoma japonicum",
            "Schizoaffective Disorde",
            "Schizophrenia",
            "Schnitzler Syndrome",
            "Sciatica",
            "Seasonal Affective Disorde",
            "Seasonal Allergic Conjunctivitis",
            "Seborrheic Dermatitis",
            "Secondary Cutaneous Bacterial Infections",
            "Secondary Hyperparathyroidism",
            "Sedation",
            "Seizure Prevention",
            "Seizures",
            "Sexual Dysfunction, SSRI Induced",
            "Shift Work Sleep Disorde",
            "Sinus Symptoms",
            "Sinusitis",
            "Sjogren's Syndrome",
            "Skin Cance",
            "Skin Disinfection, Preoperative",
            "Skin Rash",
            "Skin and Structure Infection",
            "Skin or Soft Tissue Infection",
            "Sleep Paralysis",
            "Small Bowel Bacterial Overgrowth",
            "Small Bowel or Pancreatic Fistula",
            "Smoking Cessation",
            "Social Anxiety Disorde",
            "Soft Tissue Sarcoma",
            "Sore Throat",
            "Spondyloarthritis",
            "Spondylolisthesis",
            "Squamous Cell Carcinoma",
            "Status Epilepticus",
            "Still's Disease",
            "Stomach Cance",
            "Stomach Ulce",
            "Strep Throat",
            "Streptococcal Infection",
            "Subarachnoid Hemorrhage",
            "Submental Fullness",
            "Sunburn",
            "Supraventricular Tachycardia",
            "Surgical Prophylaxis",
            "Swine Flu",
            "Systemic Lupus Erythematosus",
            "Systemic Mastocytosis",
            "Systemic Sclerosis",
            "TSH Suppression",
            "Tardive Dyskinesia",
            "Temporomandibular Joint Disorde",
            "Tendonitis",
            "Testicular Cance",
            "Thrombocythemia",
            "Thromboembolic Stroke Prophylaxis",
            "Thyroid Cance",
            "Thyrotoxicosis",
            "Tic Disorde",
            "Tinea Barbae",
            "Tinea Capitis",
            "Tinea Corporis",
            "Tinea Cruris",
            "Tinea Pedis",
            "Tinea Versicol",
            "Tinnitus",
            "Tonsillitis/Pharyngitis",
            "Topical Disinfection",
            "Tourette's Syndrome",
            "Transient Ischemic Attack",
            "Traveler's Diarrhea",
            "Trichomoniasis",
            "Trichotillomania",
            "Trigeminal Neuralgia",
            "Tuberculosis, Latent",
            "Turner's Syndrome",
            "Ulcerative Colitis",
            "Ulcerative Colitis, Active",
            "Ulcerative Colitis, Maintenance",
            "Ulcerative Proctitis",
            "Underactive Thyroid",
            "Undifferentiated Connective Tissue Disease",
            "Upper Limb Spasticity",
            "Upper Respiratory Tract Infection",
            "Urinary Incontinence",
            "Urinary Tract Infection",
            "Urinary Tract Stones",
            "Urticaria",
            "Uterine Bleeding",
            "Uterine Fibroids",
            "Uveitis",
            "Vaginal Yeast Infection",
            "Varicella-Zoste",
            "Varicose Veins",
            "Ventricular Arrhythmia",
            "Ventricular Fibrillation",
            "Ventricular Tachycardia",
            "Vertig",
            "Vitamin B12 Deficiency",
            "Vitamin D Deficiency",
            "Vitamin K Deficiency",
            "Vitamin/Mineral Supplementation and Deficiency",
            "Vitamin/Mineral Supplementation during Pregnancy/Lactation",
            "Vulvodynia",
            "Warts",
            "Wegener's Granulomatosis",
            "Weight Loss",
            "Wilson's Disease",
            "Wolff-Parkinson-White Syndrome",
            "Women (oxybutynin)",
            "Wound Cleansing",
            "Xerostomia",
            "Yellow Fever Prophylaxis",
            "Zollinger-Ellison Syndrome",
            "acial Lipoatrophy",
            "acial Wrinkles",
            "actor IX Deficiency",
            "ailure to Thrive",
            "amilial Cold Autoinflammatory Syndrome",
            "amilial Mediterranean Feve",
            "atigue",
            "cal Segmental Glomerulosclerosis",
            "emale Infertility",
            "eve",
            "ge (amlodipine / valsartan)",
            "ge HCT (amlodipine / hydrochlorothiazide / valsartan)",
            "ibromyalgia",
            "lic Acid Deficiency",
            "llicle Stimulation",
            "mance Anxiety",
            "me",
            "min / pioglitazone)",
            "min / rosiglitazone)",
            "min / saxagliptin)",
            "min / sitagliptin)",
            "min)",
            "mist (",
            "moterol / mometasone)",
            "moterol)",
            "mulation) (phenylephrine)",
            "t Care",
            "t Pac with Cyclobenzaprine (cyclobenzaprine)",
            "ungal Infection Prophylaxis",
            "von Willebrand's Disease",
            "zen Shoulde",
    };
//    private HashMap<String, Float> hash;
    //private RatingBar ratingBar;
    private ArrayList <String> symptoms = new ArrayList<String>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_symptoms);

        Spinner spin = (Spinner) findViewById(R.id.symSpinner);

        Button upload = (Button) findViewById(R.id.symUpData);
 //       hash = new HashMap<String, Float>();
 //       for(int i = 0; i < symptomsList.length; i++){
 //           hash.put(symptomsList[i], (float) 0.0);
 //       }

        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this, R.array.symptoms_array, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spin.setAdapter(adapter);
        spin.setOnItemSelectedListener(this);

        //ratingBar = (RatingBar) findViewById(R.id.symRatingBar);
        //ratingBar.setOnRatingBarChangeListener(new RatingBar.OnRatingBarChangeListener() {


//            @Override
//            public void onRatingChanged(RatingBar ratingBar, float rating,
//                                        boolean fromUser) {
////                te = ratingBar.getRating();
//                value = ratingBar.getRating();
//                text = spin.getSelectedItem().toString();
//                hash.put(text, value);
//
//                //Toast.makeText(SymptomsActivity.this, String.valueOf(value), Toast.LENGTH_LONG).show();
//            }
//        });

        upload.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                try {
                    List <String> drugName = diagnosis(symptoms.get(0), v.getContext());

                    TextView drug = (TextView) findViewById(R.id.drug);
                    // display all record's drug value in list in text view
                    drug.setText(drugName.toString());
                } catch (IOException | CsvException e) {
                    throw new RuntimeException(e);
                }
//                TextView RespiRateView = (TextView) findViewById(R.id.RespiRateValTextView);
//                db_handler = new DatabaseWorking();
//                db_handler.create_logging_database();
//                db_handler.create_logging_table();
//                boolean status = true;
//
//                for(int i = 0; i < symptomsList.length; i++){
//                    status = status ^ db_handler.upload_logging_data(hash.get(symptomsList[i]), symptomsList[i]);
//                }
//                if(!status){
//                    Log.d("Failed","Data Upload Failed");
//                    Toast.makeText(SymptomsActivity.this, "Log Failed", Toast.LENGTH_LONG).show();
//                }
            }
        });

    }

    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
        String selected_item = (String) adapterView.getItemAtPosition(i);
        symptoms.clear();
        symptoms.add(selected_item);
//        Float rating = hash.get(selected_item);
//        ratingBar.setRating(rating);
    }

    @Override
    public void onNothingSelected(AdapterView<?> adapterView) {

    }

    public static List<String> solve(List<Record> records, String query) {
        query = query.toLowerCase();
        String finalQuery = query;
        return records.stream()
                .filter(record -> record.condition.equals(finalQuery))
                .sorted(Comparator.comparingDouble(Record::getValue).reversed())
                .map(record -> record.drugName).limit(5)
                .collect(Collectors.toList());
    }

    static class Record {
        String condition;
        String drugName;
        double value;

        Record(String[] data) {
            this.condition = data[1].toLowerCase();
            this.drugName = data[2];
            if (data[3] != null && !data[3].isEmpty()) {
                this.value = Double.parseDouble(data[3]);
            } else {
                this.value = 0; // or some default value
            }
        }

            double getValue() {
            return value;
        }


    }
}